# Generated by Django 5.0.7 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmClosingBalances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_amount', models.FloatField()),
                ('cashier_amount', models.FloatField()),
                ('verification_amount', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmDrops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('positive', models.BooleanField(default=False)),
                ('comment', models.CharField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPaymentMethods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.BinaryField(null=True)),
                ('in_situation', models.BooleanField()),
                ('is_tpe', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPaymentMethodsAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('in_form', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='paid')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPaymentsAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmClientDebts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('is_refund', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('cm_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_debts', to='users.cmclients')),
            ],
        ),
    ]
