# Generated by Django 5.0.7 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        ('pos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmclientdebts',
            name='cm_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_debts', to='pos.cmshifts'),
        ),
        migrations.AddField(
            model_name='cmclosingbalances',
            name='cm_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_balances', to='pos.cmshifts'),
        ),
        migrations.AddField(
            model_name='cmclosingbalances',
            name='verification_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_ver_employee', to='users.cmemployees'),
        ),
        migrations.AddField(
            model_name='cmdrops',
            name='cm_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drops', to='users.cmemployees'),
        ),
        migrations.AddField(
            model_name='cmdrops',
            name='cm_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drops', to='pos.cmshifts'),
        ),
        migrations.AddField(
            model_name='cmpaymentmethods',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_methods', to='payments.cmpaymentmethods'),
        ),
        migrations.AddField(
            model_name='cmclosingbalances',
            name='cm_payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_balances', to='payments.cmpaymentmethods'),
        ),
        migrations.AddField(
            model_name='cmclientdebts',
            name='cm_payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_debts', to='payments.cmpaymentmethods'),
        ),
        migrations.AddField(
            model_name='cmpaymentmethodsattributes',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_method_attributte', to='payments.cmpaymentmethods'),
        ),
        migrations.AddField(
            model_name='cmpayments',
            name='cm_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='orders.cmorders'),
        ),
        migrations.AddField(
            model_name='cmpayments',
            name='cm_payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.cmpaymentmethods'),
        ),
        migrations.AddField(
            model_name='cmpayments',
            name='cm_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift', to='pos.cmshifts'),
        ),
        migrations.AddField(
            model_name='cmclientdebts',
            name='cm_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_debts', to='payments.cmpayments'),
        ),
        migrations.AddField(
            model_name='cmpaymentsattribute',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_attribute', to='payments.cmpayments'),
        ),
        migrations.AddField(
            model_name='cmpaymentsattribute',
            name='payment_method_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_method_attribute', to='payments.cmpaymentmethodsattributes'),
        ),
    ]
