# Generated by Django 5.0.7 on 2024-08-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kds', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmClients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('cm_features', models.ManyToManyField(related_name='role_features', to='users.cmfeature')),
            ],
        ),
        migrations.CreateModel(
            name='CmEmployees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('has_pos', models.BooleanField(default=True)),
                ('pin_code', models.CharField(max_length=255)),
                ('badge_number', models.CharField(max_length=255, null=True)),
                ('poste', models.CharField(max_length=255, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('preparation_display', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_preparation_display', to='kds.cmpreparationdisplay')),
                ('cm_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='users.cmrole')),
            ],
        ),
    ]
