version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: CaisseManager
      POSTGRES_USER: cm_user
      POSTGRES_PASSWORD: CmPass
    networks:
      - my_new_bridge_network

  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations --noinput &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DEBUG: 'true'
      DJANGO_SECRET_KEY: 'django-insecure-s55o#o52)@imxy11m(5u+e3mkr(x8lawi9^m&ielua!3p^zpdj'
      DB_NAME: CaisseManager
      DB_USER: cm_user
      DB_PASSWORD: CmPass
      DB_HOST: db
      DB_PORT: 5432
      API_KEY: '0psMoO10.9tDw2uWezk19XJ0ECuDC231DaIPgjixJ'
    networks:
      - my_new_bridge_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: cm_user
      RABBITMQ_DEFAULT_PASS: CmPass
    networks:
      - my_new_bridge_network

  celery:
    build: .
    command: celery -A server worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
    environment:
      DEBUG: 'true'
      DJANGO_SECRET_KEY: 'django-insecure-s55o#o52)@imxy11m(5u+e3mkr(x8lawi9^m&ielua!3p^zpdj'
      DB_NAME: CaisseManager
      DB_USER: cm_user
      DB_PASSWORD: CmPass
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://cm_user:CmPass@rabbitmq:5672//
    networks:
      - my_new_bridge_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my_new_bridge_network

  print-service:
    build:
      context: ./printing-service  # Path to the printing service directory
    ports:
      - "5000:5000"
    networks:
      - my_new_bridge_network
    environment:
      RABBITMQ_BROKER_URL: amqp://cm_user:CmPass@rabbitmq:5672//

  socket-service:
    build:
      context: ./socket-service  # Path to the socket service directory
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
    networks:
      - my_new_bridge_network

networks:
  my_new_bridge_network:
    external: true

volumes:
  postgres_data: