# Generated by Django 5.0.7 on 2024-08-16 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmKdsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(null=True)),
                ('status', models.CharField(default='New')),
                ('cancelled', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmKdsOrderline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_done', models.BooleanField(default=False)),
                ('quantity_cancelled', models.FloatField(default=0.0)),
                ('suiteCommande', models.BooleanField(default=False)),
                ('suiteOrdred', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPreparationDisplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_pilotage', models.BooleanField(null=True)),
                ('average_time', models.IntegerField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmPreparationDisplayStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_to_preparate', models.BooleanField(null=True)),
                ('is_done', models.BooleanField(null=True)),
                ('color', models.CharField(null=True)),
                ('sequence', models.IntegerField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
