# Generated by Django 5.0.7 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kds', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmkdsorder',
            name='cm_pos_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kds_order', to='orders.cmorders'),
        ),
        migrations.AddField(
            model_name='cmkdsorderline',
            name='cm_kds_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kds_order_orderline', to='kds.cmkdsorder'),
        ),
        migrations.AddField(
            model_name='cmkdsorderline',
            name='cm_pos_orderline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kds_orderline', to='orders.cmorderline'),
        ),
        migrations.AddField(
            model_name='cmkdsorderline',
            name='combo_prod_ids',
            field=models.ManyToManyField(related_name='combo_prod_ids', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='cmkdsorder',
            name='cm_preparation_display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_preparation_display', to='kds.cmpreparationdisplay'),
        ),
        migrations.AddField(
            model_name='cmpreparationdisplay',
            name='stage_ids',
            field=models.ManyToManyField(related_name='stage_ids', to='kds.cmpreparationdisplaystage'),
        ),
        migrations.AddField(
            model_name='cmkdsorder',
            name='cm_preparation_display_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_preparation_display_display', to='kds.cmpreparationdisplaystage'),
        ),
    ]
