# Generated by Django 5.0.7 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmOrderType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField()),
                ('select_table', models.BooleanField(default=True)),
                ('select_deliveryboy', models.BooleanField(default=False)),
                ('select_client', models.BooleanField(default=False)),
                ('in_mobile', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('onPlace', 'On Place'), ('takeAway', 'Take Away')], default='onPlace', max_length=10)),
                ('icon', models.BinaryField(null=True)),
                ('image', models.BinaryField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CmOrderLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0, null=True)),
                ('customer_index', models.IntegerField()),
                ('notes', models.TextField()),
                ('qty', models.FloatField()),
                ('cancelled_qty', models.FloatField(default=0.0)),
                ('suite_commande', models.BooleanField(default=False)),
                ('suite_ordred', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_ordred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('combo_prods', models.ManyToManyField(related_name='combo_prods', to='products.productvariant')),
                ('combo_supps', models.ManyToManyField(related_name='combo_supps', to='products.productvariant')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariant')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.uom')),
            ],
        ),
        migrations.CreateModel(
            name='CmOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=255, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('customer_count', models.IntegerField()),
                ('one_time', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cmclients')),
            ],
        ),
    ]
