# Generated by Django 5.0.7 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('kds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=1)),
                ('is_displayed', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_archived', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_active', models.BooleanField()),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price_ttc', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('in_mobile_pos', models.BooleanField(default=True)),
                ('in_pos', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('barcode', models.CharField()),
                ('is_archived', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=255)),
                ('is_menu', models.BooleanField()),
                ('is_quantity_check', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tax')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField()),
                ('is_supplement', models.BooleanField()),
                ('number_of_products', models.IntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariant')),
                ('product_variants', models.ManyToManyField(related_name='menu_options', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenPoste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('by_ip', models.BooleanField(default=False)),
                ('screen', models.BooleanField(default=False)),
                ('printer_ip', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('screen_poste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kitchen_poste_screen', to='kds.cmpreparationdisplay')),
                ('product_variants', models.ManyToManyField(related_name='kitchen_products', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('extra_price', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
                ('variant_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariantattribute')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_attributes',
            field=models.ManyToManyField(to='products.productvariantattributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cm_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.uom'),
        ),
    ]
